AWSTemplateFormatVersion: 2010-09-09
Description: RDS Aurora MySQL cluster.
Parameters:
    DatabaseName:
      Default: MyDatabase
      Description: The database name
      Type: String
      MinLength: '1'
      MaxLength: '64'
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

    DatabaseInstanceType:
        Default: db.t2.small
        AllowedValues:
            - db.t2.small
            - db.t2.medium
            - db.r4.large
            - db.r4.xlarge
            - db.r4.2xlarge
            - db.r4.4xlarge
            - db.r4.8xlarge
            - db.r4.16xlarge
        Description: "The instance type to use for the database. Pricing: https://aws.amazon.com/rds/aurora/pricing/"
        Type: String
    
    DatabasePassword:
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters. Must have length 8-41.
        Description: The database admin account password. (Choose a secure password)
        MaxLength: '41'
        MinLength: '8'
        NoEcho: 'true'
        Type: String
    
    DatabaseUsername:
        Default: "wordpress"
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters. Must have length 1-16
        Description: The database admin account user name.
        MaxLength: '16'
        MinLength: '1'
        Type: String
    EC2VPC:  
      Type: AWS::EC2::VPC::Id  
      Description: Select a VPC for database 
    
    EC2Subnet:  
      Type: AWS::EC2::Subnet::Id  
      Description: Select a second subnet for database 
    
    EC2Subnet2:  
      Type: AWS::EC2::Subnet::Id  
      Description: Select a first subnet for database  
    
    DatabaseSecurityGroup:  
      Type:  AWS::EC2::SecurityGroup::Id 
      Description: Select a security-group to launch database Instance
      
Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label:
                default: Database Configuration
              Parameters:
                - DatabaseInstanceType
                - DatabaseName
                - DatabaseUsername
                - DatabasePassword
        ParameterLabels:
            DatabaseName:
              default: Database name
            DatabaseInstanceType:
                default: Database Instance Type
            DatabasePassword:
                default: Database Password
            DatabaseUsername:
                default: Database Username

Resources:
    StackAlarmTopic:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: Stack Alarm Topic

    DatabaseSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: CloudFormation managed DB subnet group.
            SubnetIds:
                - !Ref EC2Subnet
                - !Ref EC2Subnet2

    ParameterGroup:
        Type: "AWS::RDS::DBParameterGroup"
        Properties: 
            Description: Prisma DB parameter group 
            Family: aurora-mysql5.7
            Parameters:
                max_connections: 300

    DatabaseCluster:
        Type: AWS::RDS::DBCluster
        Properties:
            Engine: aurora-mysql
            MasterUsername:
              Ref: DatabaseUsername
            DatabaseName:
              Ref: DatabaseName
            MasterUserPassword:
              Ref: DatabasePassword
            BackupRetentionPeriod: 35
            PreferredBackupWindow: 02:00-03:00
            PreferredMaintenanceWindow: mon:03:00-mon:04:00
            DBSubnetGroupName:
              Ref: DatabaseSubnetGroup
            VpcSecurityGroupIds:
              - Ref: DatabaseSecurityGroup
            DBClusterParameterGroupName: default.aurora-mysql5.7

    DatabaseInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            Engine: aurora-mysql
            DBClusterIdentifier:
                Ref: DatabaseCluster
            DBInstanceClass:
                Ref: DatabaseInstanceType
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup    
            DBParameterGroupName: !Ref ParameterGroup
            PubliclyAccessible: "false"
            DBInstanceIdentifier: !Ref DatabaseName
            
    DatabaseSecondInstance:
        Type: AWS::RDS::DBInstance
        DependsOn: 
          - DatabaseInstance
        Properties:
            Engine: aurora-mysql
            DBClusterIdentifier:
                Ref: DatabaseCluster
            DBInstanceClass:
                Ref: DatabaseInstanceType
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup    
            DBParameterGroupName: !Ref ParameterGroup
            PubliclyAccessible: "false"
            DBInstanceIdentifier: Database2
            

    DatabaseCPUAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Primary database CPU utilization is over 80%.
            Namespace: AWS/RDS
            MetricName: CPUUtilization
            Unit: Percent
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic

    DatabaseMemoryAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Primary database freeable memory is under 700MB.
            Namespace: AWS/RDS
            MetricName: FreeableMemory
            Unit: Bytes
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 700000000
            ComparisonOperator: LessThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic
            OKActions: 
                - Ref: StackAlarmTopic

Outputs:
    DatabaseEndpoint: 
        Description: The database endpoint
        Value: !GetAtt DatabaseCluster.Endpoint.Address
    
    DatabasePort:
        Description: The database port
        Value: !GetAtt DatabaseCluster.Endpoint.Port